"""Pydantic models defining the planning data structures."""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictInt,
    StrictStr,
    model_validator,
)


class ExecutionStrategy(StrEnum):
    """Execution strategy chosen by the LLM planner."""

    TARGETED = "targeted"
    SEQUENTIAL = "sequential"
    FULL = "full"
    MINIMAL = "minimal"
    BALANCED = "balanced"
    COMPREHENSIVE = "comprehensive"
    ADAPTIVE = "adaptive"
    EMERGENCY = "emergency"


class ExecutionStep(BaseModel):
    """Single step in an execution plan representing a tool invocation."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    tool: StrictStr = Field(
        ...,
        min_length=1,
        max_length=128,
        description="Name of the tool to invoke.",
    )
    priority: StrictInt = Field(
        ...,
        ge=1,
        description="Priority/sequence order of execution.",
    )
    reason: StrictStr = Field(
        ...,
        min_length=1,
        max_length=1024,
        description="Reasoning for selecting this tool.",
    )
    step_id: StrictStr = Field(
        default="",
        description="Unique identifier for this execution step.",
    )
    dependencies: tuple[StrictStr, ...] = Field(
        default_factory=tuple,
        description="Step IDs or tool names that this step depends on.",
    )
    conditions: tuple[StrictStr, ...] = Field(
        default_factory=tuple,
        description="Conditions that must be met to run this step.",
    )
    expected_output: StrictStr = Field(
        default="",
        description="Expected outcome or artifact generated by the step.",
    )
    retry_policy: dict[str, Any] = Field(
        default_factory=dict,
        description="Configuration rules for retrying on failure.",
    )
    timeout: StrictInt = Field(
        default=30,
        ge=1,
        description="Maximum execution time limit in seconds.",
    )
    estimated_cost: float = Field(
        default=0.0,
        description="Estimated monetary or token cost of executing the step.",
    )
    estimated_value: float = Field(
        default=0.0,
        description="Estimated intelligence value of executing the step.",
    )

    @model_validator(mode="before")
    @classmethod
    def preprocess_step(cls, data: Any) -> Any:
        """Preprocess keys to ensure backwards compatibility and proper types."""
        if not isinstance(data, dict):
            return data

        # Map tool_name to tool if present
        if "tool_name" in data and "tool" not in data:
            data["tool"] = data["tool_name"]

        # Default step_id based on tool and priority if not specified
        if not data.get("step_id"):
            tool_val = data.get("tool", "step")
            prio_val = data.get("priority", 1)
            data["step_id"] = f"{tool_val}_{prio_val}"

        # Coerce lists/tuples for dependencies and conditions
        for field in ("dependencies", "conditions"):
            if field in data and isinstance(data[field], list):
                data[field] = tuple(data[field])
            elif field not in data:
                # support mapping execution_conditions to conditions
                if field == "conditions" and "execution_conditions" in data:
                    ec = data["execution_conditions"]
                    data["conditions"] = tuple(ec) if isinstance(ec, list) else ec
                else:
                    data[field] = ()

        return data


class ExecutionPlan(BaseModel):
    """The structured execution plan generated by the planner."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    goal: StrictStr = Field(
        ...,
        min_length=1,
        max_length=512,
        description="Overall objective for analyzing the email.",
    )
    strategy: ExecutionStrategy = Field(
        ...,
        description="Strategy mode chosen for analysis.",
    )
    steps: tuple[ExecutionStep, ...] = Field(
        ...,
        description="Ordered sequence of execution steps.",
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score for this execution plan.",
    )

    @model_validator(mode="before")
    @classmethod
    def preprocess_plan(cls, data: Any) -> Any:
        """Preprocess keys to allow string/list coercions in strict mode."""
        if not isinstance(data, dict):
            return data
        strategy_val = data.get("strategy")
        if isinstance(strategy_val, str):
            try:
                data["strategy"] = ExecutionStrategy(strategy_val)
            except ValueError:
                pass
        steps_val = data.get("steps")
        if isinstance(steps_val, list):
            data["steps"] = tuple(steps_val)
        return data


class ToolSelection(BaseModel):
    """Metadata of an available tool exposed to the planner context."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    name: StrictStr = Field(..., min_length=1, max_length=128)
    description: StrictStr = Field(..., min_length=1, max_length=1024)
    capabilities: tuple[StrictStr, ...] = Field(default_factory=tuple)


class PlannerContext(BaseModel):
    """Current state context serialized for the LLM planner."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    email_id: StrictStr | None = Field(default=None, max_length=128)
    email_subject: StrictStr | None = Field(default=None, max_length=512)
    email_sender: StrictStr | None = Field(default=None, max_length=256)
    email_body_summary: StrictStr | None = Field(default=None, max_length=4096)
    available_tools: tuple[ToolSelection, ...] = Field(default_factory=tuple)
    execution_history: tuple[dict[str, Any], ...] = Field(default_factory=tuple)
    accumulated_evidence: tuple[dict[str, Any], ...] = Field(default_factory=tuple)

    @model_validator(mode="before")
    @classmethod
    def preprocess_context(cls, data: Any) -> Any:
        """Preprocess keys to allow list-to-tuple coercions in strict mode."""
        if not isinstance(data, dict):
            return data
        for field in ("available_tools", "execution_history", "accumulated_evidence"):
            val = data.get(field)
            if isinstance(val, list):
                data[field] = tuple(val)
        return data


class PlanningOptions(BaseModel):
    """Configurable runtime parameters for LLM request options."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    temperature: float = Field(default=0.0, ge=0.0, le=2.0)
    max_tokens: StrictInt = Field(default=1024, ge=1)
    timeout: float = Field(default=30.0, ge=0.1)
    retry_count: StrictInt = Field(default=3, ge=0)
    retry_delay: float = Field(default=1.0, ge=0.0)


class PlannerRequest(BaseModel):
    """Wrapper encapsulating planner request context and configurations."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    context: PlannerContext
    options: PlanningOptions = Field(default_factory=PlanningOptions)


class PlannerUsage(BaseModel):
    """Usage stats reporting prompt and completion tokens."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    prompt_tokens: StrictInt | None = Field(default=None, ge=0)
    completion_tokens: StrictInt | None = Field(default=None, ge=0)
    total_tokens: StrictInt | None = Field(default=None, ge=0)


class ProviderResponse(BaseModel):
    """Raw wrapper for a response from the LLM provider interface."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    content: StrictStr = Field(...)
    usage: PlannerUsage = Field(default_factory=PlannerUsage)
    metadata: dict[str, Any] = Field(default_factory=dict)


class PlannerMetadata(BaseModel):
    """Execution metadata for a completed planning run."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    provider: StrictStr = Field(..., min_length=1, max_length=128)
    model: StrictStr = Field(..., min_length=1, max_length=128)
    latency_ms: StrictInt = Field(..., ge=0)
    timestamp: StrictStr = Field(..., min_length=1, max_length=64)
    additional_metadata: dict[str, Any] = Field(default_factory=dict)


class PlannerResponse(BaseModel):
    """Internal model wrapper validating structured LLM parser output."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    plan: ExecutionPlan
    success: StrictBool = Field(default=True)
    error_message: StrictStr | None = Field(default=None, max_length=1024)


class PlanningResult(BaseModel):
    """The structured result of the planner orchestration service."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    plan: ExecutionPlan | None = Field(default=None)
    metadata: PlannerMetadata
    usage: PlannerUsage
    success: StrictBool = Field(default=True)
    error_message: StrictStr | None = Field(default=None, max_length=1024)
